language: python
python:
  - "2.7"
  - "3.6"

services:
  - mysql

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS DB;'
  - mysql -u root --password='' < create.sql
  - mysql -u root --password='' < fake_data.sql
  - echo "MYSQL_DATABASE_PASSWORD = ''" >> config.py

script:
  - coverage run --branch test.py
  - cat test_log.txt
  - coverage report -m
