language: python
python:
  - "2.7"
  - "3.6"

services:
  - mysql

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_install:
#  - mysql -e 'CREATE DATABASE IF NOT EXISTS DB;'
  - mysql -u root < create.sql
  - mysql -u root < fake_data.sql
script:
#  pytest

  coverage run --branch test.py
#  - echo "NO SCRIPY 2 RUN"